允许搜刮的世界:
  - world
撤离范围: 5
撤离时间: 10
撤离传送点:
  world: world
  x: -1018.0
  y: 54.0
  z: -786.0
撤离点:
  loc1:
    world: world
    x: -1033.0
    y: 50.0
    z: -768.0
箱子搜刮间隔: 10
箱子金币奖励:
  普通:
    min: 1.0
    max: 5.0
  高级:
    min: 6.0
    max: 10.0
  稀有:
    min: 11.0
    max: 15.0
  史诗:
    min: 16.0
    max: 20.0
  传奇:
    min: 21.0
    max: 25.0
  绝世:
    min: 26.0
    max: 30.0
  神话:
    min: 31.0
    max: 35.0
公告箱子品阶:
  - 传奇
  - 绝世
  - 神话
箱子数据:
  普通: { }
  高级: { }
  稀有: { }
  史诗: { }
  传奇: { }
  绝世: { }
  神话: { }