允许搜刮的世界:
  - world
撤离范围: 5
撤离点:
  loc1:
    world: world
    x: -1033.0
    y: 50.0
    z: -768.0
箱子搜刮间隔: 10
公告箱子品阶:
  - 传奇
  - 绝世
  - 神话
箱子数据:
  普通: { }
  高级: { }
  稀有: { }
  史诗: { }
  传奇: { }
  绝世: { }
  神话: { }