name: Plunder
version: '1.0-SNAPSHOT'
main: top.mores.plunder.Plunder
api-version: '1.18'
authors: [ Mores ]
description: 搜刮
commands:
  plunder:
    description: Plunder command
    usage: /plunder <>